#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidBluetoothLE.Resource", IsApplication=true)]

namespace AndroidBluetoothLE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int DiscoverServicesButton = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int HexReadText = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int OpenServerAction = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int ReadCharacteristicButton = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int ReceivedNotificationHex = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ReceivedNotificationString = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ReconnectButton = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int RowName = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int ScanAction = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int ScanList = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int ServiceList = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int StringReadText = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int Type = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int UuidValue = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int WriteCharacteristicButton = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int WriteTextField = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int label = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DeviceView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NotifyCharacteristicView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReadCharacteristicView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ScanMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScanRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScanView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ServiceListView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ServiceRow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int WriteCharacteristicView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int CloseServer = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int OpenServer = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int StartScan = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int StopScan = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
